server:
  port: 8000
spring:
  boot:
    admin:
      # 管控台上下文路径
      context-path: /admin
      ui:
        title: xx监控平台
        # 修改网页的brand的图标和标题
#        brand: "<img src='assert/img/icon-spring-boot-admin.svg'><span>应用监控管理</span>"

  #服务端也搞个账号
  security:
    user:
      name: admin
      password: admin