server:
  port: 9999
  servlet:
    context-path: /demo
#请求编码
  tomcat:
    uri-encoding: UTF-8
  ssl:
    key-store: d:\\test2\\sang.p12
    key-alias: myhttps
    key-store-password: 123456
filePath: d:\\test

#https

spring:
  profiles:
    active: dev
