spring:
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/test?useUniCode=true&characterEncoding=utf8&useSSL=false
  #    driverClassName: com.mysql.jdbc.Driver
  #    username: admin
  #    password: admin
  jpa:
    database: H2
    show-sql: true
    hibernate:
      naming:   #命名策略
#        implicit-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  #无修改命名
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy   #遇到大写字母 加”_”的命名
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 9999


#  ddl-auto:create----每次运行该程序，没有表格会新建表格，表内有数据会清空
#
#  ddl-auto:create-drop----每次程序结束的时候会清空表,生产环境注意,危险
#
#  ddl-auto:update----每次运行程序，没有表格会新建表格，表内原有数据不会清空，只会更新
#
#  ddl-auto:validate----运行程序会校验数据与数据库的字段类型是否相同，不同会报错
