spring:
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            #调度器实例名称
            instanceName: clusteredScheduler
            #调度器实例编号自动生成,手动需保持唯一性
            instanceId: AUTO
          jobStore:
            # MySql持久化方式,才支持集群
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #MSSQL	:	org.quartz.impl.jdbcjobstore.MSSQLDelegate
            #HSQLDB	:	org.quartz.impl.jdbcjobstore.HSQLDBDelegate
            #Oracle	:	org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #quartz相关数据表前缀(默认qrtz_)
            #tablePrefix:
           #开启分布式部署(将instanceId: AUTO,ClusterManager负责初始化分布式节点),通知Scheduler实例要它参与到一个集群当中
            isClustered: true
            # 分布式节点有效性检查时间间隔
            # 可以检测一个失败的Scheduler实例，且当前 Scheduler会以此来接管任何执行失败并可恢复的Job。通过检入操作，Scheduler 也会更新自身的状态记录。
            # 默认值是 15000 (即15 秒)。
            clusterCheckinInterval: 10000
            #分布式配置是否使用
            useProperties: false
          threadPool:
            #线程池实现类
            class: org.quartz.simpl.SimpleThreadPool
            #最大并发线程数量
            threadCount: 20
            #线程优先级
            threadPriority: 5
            #配置为守护线程，设置后任务将不会执⾏
            makeThreadsDaemons: true
            ##配置是否启动⾃动加载数据库内的定时任务，默认true
            threadsInheritContextClassLoaderOfInitializingThread: true
    #存储方式，数据库持久化
    job-store-type: jdbc
    #设置调度器⾃动运⾏	(default:true)
    autoStartup: true
      #数据库初始化模式
    jdbc:
      initialize-schema: never
     #/项⽬启动完成后，等待2秒后开始执⾏调度器初始化
    startup-delay: 2
    #设置覆盖已存在的任务(default:true)
    overwrite-existing-jobs: true
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?allowMultiQueries=true&characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      max-lifetime: 1800000


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.cxy.demo.demoquartz.entity
  configuration:
    map-underscore-to-camel-case: true



